export default {
  menuList: [
    {
      index: 1,
      id: '10001',
      parentId: null,
      menuName: '权限管理',
      menuIcon: '',
      menuRoute: '',
      menuPath: '/',
      menuAlias: '',
      enable: 1,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 11,
      id: '100011',
      parentId: 10001,
      menuName: '用户管理',
      menuIcon: '',
      menuRoute: '/authority/user',
      menuPath: 'views/authority/user',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 12,
      id: '100012',
      parentId: 10001,
      menuName: '菜单管理',
      menuIcon: '',
      menuRoute: '/authority/menu',
      menuPath: 'views/authority/menu',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 13,
      id: '100013',
      parentId: 10001,
      menuName: '角色管理',
      menuIcon: '',
      menuRoute: '/authority/role',
      menuPath: 'views/authority/role',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 14,
      id: '100014',
      parentId: 10001,
      menuName: '终端管理',
      menuIcon: '',
      menuRoute: '/authority/terminal',
      menuPath: 'views/authority/terminal',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 15,
      id: '100015',
      parentId: 10001,
      menuName: '产品管理',
      menuIcon: '',
      menuRoute: '/authority/produce',
      menuPath: 'views/authority/produce',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 16,
      id: '100016',
      parentId: 10001,
      menuName: '动态路由',
      menuIcon: '',
      menuRoute: '/authority/route',
      menuPath: 'views/authority/route',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 2,
      id: '10002',
      parentId: null,
      menuName: '日志管理',
      menuIcon: '',
      menuRoute: '',
      menuPath: '/',
      menuAlias: '',
      enable: 1,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    },
    {
      index: 21,
      id: '100021',
      parentId: 10002,
      menuName: '日志记录',
      menuIcon: '',
      menuRoute: '/log/log',
      menuPath: 'views/log/log',
      menuAlias: '',
      enable: 0,
      virtual: 0,
      closable: 1,
      deep: 2,
      sort: 0
    }
  ]
}
