export default [
  {
    id: '2',
    parentId: null,
    menuRoute: null,
    menuRouteName: null,
    menuName: '平台管理',
    menuPath: null,
    menuIcon: null,
    iconType: null,
    menuType: 'iframe',
    enable: true,
    closable: null
  },

  {
    id: '2-1',
    parentId: '2',
    menuRoute: null,
    menuRouteName: null,
    menuName: '机构管理',
    menuPath: null,
    menuIcon: 'zyy-icon zyy-jggl',
    iconType: 'Local Icons',
    enable: null,
    closable: null
  },

  {
    id: '2-1-1',
    parentId: '2-1',
    menuRouteName: 'platform/user/account',
    menuRoute: 'platform/user/account',
    menuName: '账号管理',
    menuPath: 'views/platform/user/account',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-1-2',
    parentId: '2-1',
    menuRouteName: 'platform/user/organization',
    menuRoute: 'platform/user/organization',
    menuName: '机构列表',
    menuPath: 'views/platform/user/organization',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },

  {
    id: '2-2',
    parentId: '2',
    menuRouteName: null,
    menuRoute: null,
    menuName: '审核管理',
    menuPath: null,
    menuIcon: 'zyy-icon zyy-shenhe',
    iconType: 'Local Icons',
    enable: null,
    closable: null
  },
  {
    id: '2-2-1',
    parentId: '2-2',
    menuRouteName: 'platform/check/qualification',
    menuRoute: 'platform/check/qualification',
    menuName: '资质认证',
    menuPath: 'views/platform/check/qualification',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-2-2',
    parentId: '2-2',
    menuRouteName: 'platform/check/service',
    menuRoute: 'platform/check/service',
    menuName: '服务开通',
    menuPath: 'views/platform/check/service',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },

  {
    id: '2-3',
    parentId: '2',
    menuRouteName: null,
    menuRoute: null,
    menuName: '基础数据',
    menuPath: null,
    menuIcon: 'zyy-icon zyy-jcsj',
    iconType: 'Local Icons',
    enable: null,
    closable: null
  },
  {
    id: '2-3-1',
    parentId: '2-3',
    menuRouteName: '2-3-1',
    menuRoute: '2-3-1',
    menuName: '药品目录',
    menuPath: process.env.VUE_APP_OPERATION_SITE + 'DrugData/DrugData',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-3-2',
    parentId: '2-3',
    menuRouteName: '2-3-2',
    menuRoute: '2-3-2',
    menuName: '给药途径',
    menuPath: process.env.VUE_APP_OPERATION_SITE + 'DrugData/Route',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-3-3',
    parentId: '2-3',
    menuRouteName: '2-3-3',
    menuRoute: '2-3-3',
    menuName: '给药频次',
    menuPath: process.env.VUE_APP_OPERATION_SITE + 'DrugData/Frequency',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-3-4',
    parentId: '2-3',
    menuRouteName: '2-3-4',
    menuRoute: '2-3-4',
    menuName: '药品单位',
    menuPath: process.env.VUE_APP_OPERATION_SITE + 'DrugData/Unit',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-3-5',
    parentId: '2-3',
    menuRouteName: '2-3-5',
    menuRoute: '2-3-5',
    menuName: '药品说明书',
    menuPath: process.env.VUE_APP_OPERATION_SITE + 'knowledgebase/web?uri=knowledgeBaseManage/drugsInstructions/drugsInstructionList.html',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-3-6',
    parentId: '2-3',
    menuRouteName: '2-3-6',
    menuRoute: '2-3-6',
    menuName: '药品说明书审核',
    menuPath: process.env.VUE_APP_OPERATION_SITE + 'knowledgebase/web?uri=knowledgeBaseExamine/drugsInstructions/instructionExamineList.html',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-4',
    parentId: '2',
    menuRouteName: null,
    menuRoute: null,
    menuName: '数据统计',
    menuPath: null,
    menuIcon: 'zyy-icon zyy-sjtj',
    iconType: 'Local Icons',
    enable: null,
    closable: null
  },
  {
    id: '2-4-1',
    parentId: '2-4',
    menuRouteName: 'platform/statistics/ywq',
    menuRoute: 'platform/statistics/ywq',
    menuName: '医网签调用',
    menuPath: 'views/platform/statistics/ywq',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-5',
    parentId: '2',
    menuRouteName: null,
    menuRoute: null,
    menuName: '平台日志',
    menuPath: null,
    menuIcon: 'zyy-icon zyy-ptrz',
    iconType: 'Local Icons',
    enable: null,
    closable: null
  },
  {
    id: '2-5-1',
    parentId: '2-5',
    menuRouteName: 'platform/logger/recordList',
    menuRoute: 'platform/logger/recordList',
    menuName: '日志记录',
    menuPath: 'views/platform/logger/recordList',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-5-2',
    parentId: '2-5',
    menuRouteName: '2-5-2',
    menuRoute: 'platform/logger/menu',
    menuName: '菜单管理',
    menuPath: 'views/uims/menu',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-5-3',
    parentId: '2-5',
    menuRouteName: '2-5-3',
    menuRoute: 'platform/logger/role',
    menuName: '角色管理',
    menuPath: 'views/uims/role',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '2-5-4',
    parentId: '2-5',
    menuRouteName: '2-5-4',
    menuRoute: 'platform/logger/user',
    menuName: '用户管理',
    menuPath: 'views/uims/user',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  }
]
