export default [
  {
    id: '3',
    parentId: null,
    menuRoute: null,
    menuRouteName: null,
    menuName: '互医管理',
    menuPath: null,
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: null
  },

  {
    id: '3-1',
    parentId: '3',
    menuRoute: null,
    menuRouteName: null,
    menuName: '医生管理',
    menuPath: null,
    menuIcon: 'zyy-yisheng',
    iconType: 'Zyy Icons',
    enable: null,
    closable: null
  },

  {
    id: '3-1-1',
    parentId: '3-1',
    menuRouteName: 'doctorList',
    menuRoute: 'doctorList',
    menuName: '医生列表',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/doctor/list',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-1-2',
    parentId: '3-1',
    menuRouteName: '3-1-2',
    menuRoute: '3-1-2',
    menuName: '入驻列表',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/doctor/settled',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-2',
    parentId: '3',
    menuRoute: null,
    menuRouteName: null,
    menuName: '机构管理',
    menuPath: null,
    menuIcon: 'zyy-jigou',
    iconType: 'Zyy Icons',
    enable: null,
    closable: null
  },
  {
    id: '3-2-1',
    parentId: '3-2',
    menuRouteName: 'orgList',
    menuRoute: 'orgList',
    menuName: '机构列表',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/organization/list',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-3',
    parentId: '3',
    menuRoute: null,
    menuRouteName: null,
    menuName: '用户管理',
    menuPath: null,
    menuIcon: 'zyy-yonghu',
    iconType: 'Zyy Icons',
    enable: null,
    closable: null
  },
  {
    id: '3-3-1',
    parentId: '3-3',
    menuRouteName: 'userList',
    menuRoute: 'userList',
    menuName: '用户列表',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/user/list',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-3-2',
    parentId: '3-3',
    menuRouteName: 'patientList',
    menuRoute: 'patientList',
    menuName: '患者列表',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/user/patient',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-4',
    parentId: '3',
    menuRoute: null,
    menuRouteName: null,
    menuName: '平台管理',
    menuPath: null,
    menuIcon: 'zyy-pingtai',
    iconType: 'Zyy Icons',
    enable: null,
    closable: null
  },
  {
    id: '3-4-1',
    parentId: '3-4',
    menuRouteName: 'platformDepartment',
    menuRoute: 'platformDepartment',
    menuName: '平台科室',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/platform/department',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-4-2',
    parentId: '3-4',
    menuRouteName: 'platformImages',
    menuRoute: 'platformImages',
    menuName: '平台图库',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/platform/images',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-4-3',
    parentId: '3-4',
    menuRouteName: 'platformAdvertisement',
    menuRoute: 'platformAdvertisement',
    menuName: '平台内容',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/platform/advertisement',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-5',
    parentId: '3',
    menuRoute: null,
    menuRouteName: null,
    menuName: '基础字典',
    menuPath: null,
    menuIcon: 'zyy-zidian',
    iconType: 'Zyy Icons',
    enable: null,
    closable: null
  },
  {
    id: '3-5-1',
    parentId: '3-5',
    menuRouteName: 'hospitalDictionary',
    menuRoute: 'hospitalDictionary',
    menuName: '全国医院字典',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/dictionary/national',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-5-2',
    parentId: '3-5',
    menuRouteName: 'departmentDictionary',
    menuRoute: 'departmentDictionary',
    menuName: '医院科室字典',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/dictionary/department',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-5-3',
    parentId: '3-5',
    menuRouteName: 'doctorDictionary',
    menuRoute: 'doctorDictionary',
    menuName: '全国医生字典',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/dictionary/doctor',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-5-4',
    parentId: '3-5',
    menuRouteName: 'areaDictionary',
    menuRoute: 'areaDictionary',
    menuName: '医院区域字典',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/dictionary/area',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6',
    parentId: '3',
    menuRoute: null,
    menuRouteName: null,
    menuName: '订单管理',
    menuPath: null,
    menuIcon: 'zyy-dingdan',
    iconType: 'Zyy Icons',
    enable: null,
    closable: null
  },
  {
    id: '3-6-1',
    parentId: '3-6',
    menuRouteName: 'advisoryOrder',
    menuRoute: 'advisoryOrder',
    menuName: '咨询订单',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/advisory',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6-2',
    parentId: '3-6',
    menuRouteName: 'ruturnVisitOrder',
    menuRoute: 'ruturnVisitOrder',
    menuName: '复诊订单',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/return-visit',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6-3',
    parentId: '3-6',
    menuRouteName: 'referralOrder',
    menuRoute: 'referralOrder',
    menuName: '转诊订单',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/referral',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6-4',
    parentId: '3-6',
    menuRouteName: 'consultationOrder',
    menuRoute: 'consultationOrder',
    menuName: '会诊订单',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/consultation',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6-5',
    parentId: '3-6',
    menuRouteName: 'privateDoctorOrder',
    menuRoute: 'privateDoctorOrder',
    menuName: '私人医生',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/private-doctor',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6-6',
    parentId: '3-6',
    menuRouteName: 'registeredOrder',
    menuRoute: 'registeredOrder',
    menuName: '预约挂号',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/registered',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-6-7',
    parentId: '3-6',
    menuRouteName: 'purchaseOrder',
    menuRoute: 'purchaseOrder',
    menuName: '购药订单',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/order/purchase',
    menuIcon: null,
    iconType: null,
    enable: true,
    closable: true
  },
  {
    id: '3-7',
    parentId: '3',
    menuRoute: 'advertisement',
    menuRouteName: 'advertisement',
    menuName: '广告管理',
    menuPath: process.env.VUE_APP_NETHOSPITAL + '/advertisement',
    menuIcon: 'zyy-guanggao',
    iconType: 'Zyy Icons',
    enable: null,
    closable: true
  },
]
